#%RAML 1.0 Trait

headers:
  Authorization: 
    required: true
    type: string
    example: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjJRQ1EtUW1PbHJfc1BzZ001M0pib2NjdDhHTV9mbWVhbHFndG5kUzZsLTgifQ"