#%RAML 1.0 Trait

headers:
  x-alpbnk-msgid:
    required: true
    type: string
    minLength: 36
    maxLength: 36
    example: "hdsfhjdhjxbv859sjdf76433746bbd123456"
  x-alpbnk-clientId:
    required: true
    type: string
    example: "hsdfgysdhfcdshf37er6twgsdhfjcd"
  x-alpbnk-clientSecret:
    required: true
    type: string
    example: "dsgfhaegur457r6ewsewegrfjesh"
