#%RAML 1.0 Trait

headers:
  Accept: 
    required: true
    type: string
    example: "application/json"
  Content-Type:
    required: true
    type: string
    example: "application/json"
  Accept-Language: 
    required: true
    type: string
    example: "en-US"
